name: street_performance_helper
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.4
  envied: ^1.1.1
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  fuzzywuzzy: ^1.0.0
  gsheets: ^0.5.0
  http: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
