name: jdhelper
description: "1回生大道芸データベース 検索補助アプリ"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  fuzzywuzzy: ^1.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
