name: street_performance_helper
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  fuzzywuzzy: ^1.0.0
  http: ^1.0.0
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  uses-material-design: true
